name: governed_analytics
version: "1.0.0"
config-version: 2

profile: governed_analytics

model-paths: ["models"]
test-paths: ["tests"]
clean-targets:
  - target
  - dbt_packages

vars:
  default_schema: marts
