version: 2

models:

  # ── Marts ──────────────────────────────────────────────
  - name: dim_date
    description: "Date spine 2023-01-01 to 2026-12-31."
    columns:
      - name: date_id
        tests: [unique, not_null]
      - name: date_day
        tests: [unique, not_null]

  - name: dim_users
    description: "One row per user with signup attributes."
    columns:
      - name: user_id
        tests: [unique, not_null]
      - name: country
        tests: [not_null]
      - name: device
        tests:
          - not_null
          - accepted_values:
              values: ['mobile', 'desktop', 'tablet']

  - name: dim_products
    description: "One row per product."
    columns:
      - name: product_id
        tests: [unique, not_null]
      - name: category
        tests: [not_null]
      - name: brand
        tests: [not_null]

  - name: fct_orders
    description: "One row per order with aggregated revenue and item_count."
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: user_id
        tests: [not_null]
      - name: date_id
        tests: [not_null]
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['completed', 'cancelled', 'pending']
      - name: revenue
        tests: [not_null]
      - name: item_count
        tests: [not_null]

  - name: fct_order_items
    description: "Line-level items joined with order header."
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: quantity
        tests: [not_null]
      - name: line_total
        tests: [not_null]
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['completed', 'cancelled', 'pending']
